//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestovoeZadaniye
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int gr_id { get; set; }
        public string gr_name { get; set; }
        public Nullable<float> gr_temp { get; set; }
    }
}
