//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestovoeZadaniye
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ord_id { get; set; }
        public Nullable<System.DateTime> ord_datetime { get; set; }
        public Nullable<int> ord_an { get; set; }
    
        public virtual Analysis Analysis { get; set; }
    }
}
